version: '3'

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile.n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
    volumes:
      - n8n_data:/home/node/.n8n
      # Mount your videos directory as needed
      - ./public:/videos/AffiliateMemeVids
      - shared_volume:/app/output

  remotion:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - shared_volume:/app/output
    environment:
      - NODE_ENV=production

volumes:
  n8n_data:
  shared_volume: